# Generated by Django 4.0.6 on 2022-08-15 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppExpo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
